server:
  port: 8080

zuul:
  ignoredServices: '*'
  routes:
    customer-service:
      path: /customer-service/**
      url: http://localhost:8081
# To enable eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
