server:
  port: 9411

spring:
  application:
    name: zipkin-server
  cloud:
    config:
      uri: http://localhost:8888
---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://config-server:8888
