kind: Service
apiVersion: v1
metadata:
  name: api-gateway-service
  labels:
    name: api-gateway-service
spec:
  ports:
    - nodePort: 30166
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: api-gateway-service
  type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: api-gateway-service
spec:                
  selector:         
    matchLabels:
      app: api-gateway-service
  replicas: 3        
  template:
    metadata:
      labels:        
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: rkp/api-gateway-service:1.0
          ports:
            - containerPort: 8080                
