server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rakeshpriyad/k8-microservice.git
          searchPaths: k8-api-gateway-eureka-ribbon-hystrix-config/bank/config-server-properties