zuul:
 # prefix: /api
  ignoredServices: '*'
  routes:
    customer-service:
      path: /api/customer-service/**
      serviceId: customer-service
      stripPrefix: false
    #api-gateway: /gateway/**

#zuul:
#  prefix: /api
#  ignoredServices: '*'
#  routes:
    #branch-service:
    #  path: /branch-service/**
    #  serviceId: branch-service
    #  stripPrefix: true
      #url: http://branch-service:8080
    #customers-service:/customer/**
    #api-gateway: /gateway/**
    #customer-service:
    #  path: /customer-service/**
    #  serviceId: customer-service
    #  stripPrefix: false
      #url: http://customer-service:8080
# To enable eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
      
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: ${EUREKA_URL} #${EUREKA_URI:http://eureka-server:8080/eureka}
#  instance:
#    instanceId: ${spring.application.name}:${random.value}
#    preferIpAddress: true

