zuul:
  routes:
    branch-service:
      path: /branch-service/**
      serviceId: branch-service
      stripPrefix: true
      #url: http://branch-service:8080

    customers-service:
      path: /customer-service/**
      serviceId: customer-service
      stripPrefix: true
      #url: http://customer-service:8080
# To enable eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: ${EUREKA_URL}
      defaultZone: ${EUREKA_URI:http://eureka-server:8080/eureka}
    eureka-server-port: 8080

