zuul:
  routes:
    branch-service:
      path: /branch-service/**
      url: http://branch-service:8080

    customers-service:
      path: /customer-service/**
      url: http://customer-service:8080
# To enable eureka client
eureka:
  client:
    eureka-server-port: 8080
      registerWithEureka: true
      fetchRegistry: true
