spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        hikari:
            initialization-fail-timeout: 0        
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: create
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://eureka-server:8080/eureka}
            #${EUREKA_URL}
        eureka-server-port: 8080
    instance:
        instanceId: ${spring.application.name}:${random.value}
        preferIpAddress: true